In [ ]:
#Import the library

In [29]:
import numpy

In [ ]:
#Import the model

In [78]:
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [ ]:
# Import the data set

In [21]:
from sklearn.datasets import fetch_20newsgroups
content=fetch_20newsgroups()

In [91]:
tfidf_vector=TfidfVectorizer(min_df=0.2,max_df=0.8)

In [92]:
tf=tfidf_vector.fit_transform(content.data)

In [93]:
x_train,x_test,y_train,y_test=train_test_split(tf,content.target)

In [94]:
lda=LatentDirichletAllocation(n_topics=20)

In [95]:
lda_output=lda.fit_transform(x_train,y_train)

D:\Users\manjeetnagi1\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:508: DeprecationWarning: The default value for 'learning_method' will be changed from 'online' to 'batch' in the release 0.20. This warning was introduced in 0.18.
  DeprecationWarning)


In [102]:
lda_output[0]

array([ 0.00812919,  0.00812919,  0.00812919,  0.00812919,  0.00812919,
        0.00812919,  0.00812919,  0.00812919,  0.00812919,  0.00812919,
        0.00812919,  0.00812919,  0.00812919,  0.00812919,  0.00812919,
        0.00812919,  0.84554547,  0.00812919,  0.00812919,  0.00812919])

In [111]:
lda_score=lda.transform(x_test)

In [118]:
lda_score[10]

array([ 0.81743788,  0.00960853,  0.00960853,  0.00960853,  0.00960853,
        0.00960853,  0.00960853,  0.00960853,  0.00960853,  0.00960853,
        0.00960853,  0.00960853,  0.00960853,  0.00960853,  0.00960853,
        0.00960853,  0.00960853,  0.00960853,  0.00960853,  0.00960853])

In [119]:
y_test[10]

1

In [117]:
content.target

array([7, 4, 4, ..., 3, 1, 8])